export const CAPABILITIES = Object.freeze({
    ALLOWED_BY_DEFAULT: "allowed_by_default",
    CUSTOMER_DASHBOARD: "customer_dashboard_access",
    MANAGE_IDENTITY_SOURCES: "manage_identity_sources",
    MANAGE_USER_STORES: "manage_user_stores",
    MANAGE_APPS: "manage_apps",
    MANAGE_APP_POLICIES: "manage_app_policies",
    MANAGE_PASSWORD_POLICY: "manage_password_policy",
    MANAGE_BRANDING: "manage_branding",
    MANAGE_GATEWAYS: "manage_gateways",
    MANAGE_TEMPLATES: "manage_templates",
    MANAGE_TOKENS: "manage_tokens",
    MANAGE_STATIC_CODES: "manage_static_codes",
    MANAGE_FP_POLICIES: "manage_fp_policies",
    MANAGE_PROVISIONING: "manage_provisioning",
    MANAGE_USERS: "manage_users",
    MANAGE_ROLES: "manage_roles",
    MANAGE_CAPABILITIES: "manage_capabilities",
    MANAGE_FIELD_MAPPINGS: "manage_field_mappings",
    MANAGE_USERS: "manage_users",
    MANAGE_SHARED_IDENTITY: "manage_shared_identity",
    MANAGE_SOCIAL_ACCOUNTS: "manage_social_accounts",
    MANAGE_GROUPS: "manage_groups",
    VIEW_HIGH_LEVEL_USAGE_SUMMARY: "view_high_level_usage_summary",
    VIEW_USAGE_SUMMARY_BY_USER: "view_usage_summary_by_user",
    VIEW_DETAILED_USER_AUTHENTICATION_REPORT:
        "view_detailed_user_authentication_report",
    VIEW_SINGLE_SIGN_ON_SUMMARY_BY_USER: "view_single_sign_on_summary_by_user",
    VIEW_ACTIVE_USAGE_SUMMARY: "view_active_usage_summary",
    VIEW_USER_REGISTRATION_SUMMARY: "view_user_registration_summary",
    VIEW_USER_DEVICE_PROFILES: "view_user_device_profiles",
    VIEW_USER_ADAPTIVE_AUTHENTICATION_REPORT:
        "view_user_adaptive_authentication_report",
    VIEW_SOCIAL_APPLICATIONS_USAGE_SUMMARY:
        "view_social_applications_usage_summary",
    VIEW_SOCIAL_LOGIN_DETAILS: "view_social_login_details",
    VIEW_RADIUS_USER_AUTHENTICATION_REPORT:
        "view_radius_user_authentication_report",
    MANAGE_LICENSE: "manage_license",
});
